### ISSUE TITLE
The addon does not run on Blender 2.93 Mac M1

### ISSUE THREAD

**Issue by enzyme69** [p4ymak/eyek#2]
I am trying to run the addon, but the install does not seem correct:

```
Traceback (most recent call last):
  File "/Applications/BLENDER_29/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/Users/blendersushi/Library/Application Support/Blender/2.93/scripts/addons/eyek-main/__init__.py", line 288, in register
    os.chmod(os.path.join(os.path.dirname(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/blendersushi/Library/Application Support/Blender/2.93/scripts/addons/eyek-main/eyek_mac'

```

**Comment by enzyme69** [comment]
<img width="884" alt="Screenshot 2022-11-08 at 10 21 20 am" src="https://user-images.githubusercontent.com/3952687/200436248-6ed73b51-7ab1-4585-b894-e13cd129aa9b.png">

I manually move all the files and make that folder, but still failed to run:

Python: Traceback (most recent call last):
  File "/Applications/BLENDER_29/Blender.app/Contents/Resources/2.93/scripts/startup/bl_operators/userpref.py", line 439, in execute
    mod = addon_utils.enable(self.module, default_set=True, handle_error=err_cb)
  File "/Applications/BLENDER_29/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 305, in enable
    if mod and os.path.exists(mod.__file__):
  File "/Applications/BLENDER_29/Blender.app/Contents/Resources/2.93/python/lib/python3.9/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

location: <unknown location>:-1

Is the addon running not on Mac M1?

**Comment by enzyme69** [comment]
I switch to my intel MacBookPro 2017, using Blender 2.93, the addon works. 

Is it possible to make it run on M1 / ARM Mac?

**Comment by p2or** [comment]
Hi @enzyme69,

m1 here and the add-on works fine. I guess you already figured it out, but you just need to install the [release version](https://github.com/p4ymak/eyek/releases) instead (as mentioned in the installation instructions) and allow the provided binary (`eyek_mac`) to execute on MacOS *(Settings > Privacy and Security)*. 

Cheers,
Christian
