### ISSUE TITLE
Error in 4.0 dont bake

### ISSUE THREAD

**Issue by emilsvfx** [p4ymak/eyek#6]
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by VinexN** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\jumad\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\eyek_addon\__init__.py", line 162, in execute
    bpy.ops.export_scene.obj(filepath=obj_path,
  File "D:\Games\Steam\steamapps\common\Blender\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.export_scene.obj" error, could not be found

**Comment by gryLeader** [comment]
I made it work for Blender 4.3 with this modification: 
Extract the contents of the zip and edit `__init__.py` find these lines:

```
bpy.ops.export_scene.obj(filepath=obj_path,
                                     use_selection=True,
                                     use_animation=False, 
                                     use_mesh_modifiers=True, 
                                     use_edges=True,
                                     use_smooth_groups=False,
                                     use_smooth_groups_bitflags=False,
                                     use_normals=True,
                                     use_uvs=True,
                                     use_materials=False,
                                     use_triangles=True,
                                     use_nurbs=False,
                                     use_vertex_groups=False,
                                     use_blen_objects=False,
                                     group_by_object=False,
                                     group_by_material=False,
                                     keep_vertex_order=False,
                                     global_scale=1.0,
                                     path_mode='AUTO',
                                     axis_forward='-Z',
                                     axis_up='Y')
```
                                   
replace with this code:

```
bpy.ops.wm.obj_export(filepath=obj_path,                                     
                                     export_selected_objects=True,
                                     export_animation=False, 
                                     apply_modifiers=True,
                                     export_smooth_groups=False,
                                     smooth_group_bitflags=False,
                                     export_normals=True,
                                     export_uv=True,
                                     export_materials=False,
                                     export_triangulated_mesh=True,
                                     path_mode='AUTO',
                                     export_curves_as_nurbs=False,
                                     export_vertex_groups=False,                                     
                                     export_object_groups=False,
                                     export_material_groups=False,                                     
                                     global_scale=1.0,
                                     forward_axis='NEGATIVE_Z',
                                     up_axis='Y')
```
                                     
Save the file and repack the zip, now you can use it in Blender 4.3.
